[[requests]]
name = "JSON"

method = "POST"

url = "http://localhost:8000/api/login"

body = """
{
    "username":"admin",
    "password":"password"
}
"""

[requests.headers]
Content-Type = "application/json"


[requests.expect]
status = 200
